FUNDINGTYPES = 27
INDUSTRIES = 656

UNIQ_INDUSTRIES = ["3D Printing", "3D Technology", "A/B Testing", "Accounting", "Ad Exchange", "Ad Network",
                   "Ad Retargeting", "Ad Server", "Ad Targeting", "Adult", "Advanced Materials", "Adventure Travel",
                   "Advertising", "Advertising Platforms", "Advice", "Aerospace", "Affiliate Marketing", "AgTech",
                   "Agriculture", "Air Transportation", "Alternative Medicine", "American Football",
                   "Amusement Park and Arcade", "Analytics", "Android", "Angel Investment", "Animal Feed", "Animation",
                   "App Discovery", "App Marketing", "Application Performance Management",
                   "Application Specific Integrated Circuit (ASIC)", "Apps", "Aquaculture", "Architecture",
                   "Archiving Service", "Art", "Artificial Intelligence", "Asset Management", "Assisted Living",
                   "Assistive Technology", "Association", "Auctions", "Audio", "Augmented Reality", "Auto Insurance",
                   "Automotive", "Autonomous Vehicles", "B2B", "B2C", "Baby", "Banking", "Basketball", "Battery",
                   "Beauty", "Big Data", "Billing", "Biofuel", "Bioinformatics", "Biomass Energy", "Biometrics",
                   "Biopharma", "Biotechnology", "Bitcoin", "Blockchain", "Blogging Platforms", "Brand Marketing",
                   "Brewing", "Broadcasting", "Browser Extensions", "Building Maintenance", "Building Material",
                   "Business Development", "Business Information Systems", "Business Intelligence", "Business Travel",
                   "CAD", "CMS", "CRM", "Call Center", "Cannabis", "Car Sharing", "Career Planning", "Casino",
                   "Casual Games", "Celebrity", "Charity", "Charter Schools", "Chemical", "Chemical Engineering",
                   "Child Care", "Children", "CivicTech", "Civil Engineering", "Classifieds", "Clean Energy",
                   "CleanTech", "Clinical Trials", "Cloud Computing", "Cloud Data Services", "Cloud Infrastructure",
                   "Cloud Management", "Cloud Security", "Cloud Storage", "Coffee", "Collaboration",
                   "Collaborative Consumption", "College Recruiting", "Comics", "Commercial", "Commercial Insurance",
                   "Commercial Lending", "Commercial Real Estate", "Communication Hardware",
                   "Communications Infrastructure", "Communities", "Compliance", "Computer", "Computer Vision",
                   "Concerts", "Construction", "Consulting", "Consumer", "Consumer Applications",
                   "Consumer Electronics", "Consumer Goods", "Consumer Lending", "Consumer Research",
                   "Consumer Reviews", "Consumer Software", "Contact Management", "Content", "Content Creators",
                   "Content Delivery Network", "Content Discovery", "Content Marketing", "Content Syndication",
                   "Continuing Education", "Cooking", "Corporate Training", "Cosmetic Surgery", "Cosmetics", "Coupons",
                   "Courier Service", "Coworking", "Craft Beer", "Creative Agency", "Credit", "Credit Bureau",
                   "Credit Cards", "Crowdfunding", "Crowdsourcing", "Cryptocurrency", "Customer Service",
                   "Cyber Security", "Cycling", "DIY", "DRM", "DSP", "Data Center", "Data Center Automation",
                   "Data Integration", "Data Mining", "Data Storage", "Data Visualization", "Database", "Dating",
                   "Debit Cards", "Delivery", "Delivery Service", "Dental", "Desktop Apps", "Developer APIs",
                   "Developer Platform", "Developer Tools", "Diabetes", "Dietary Supplements", "Digital Entertainment",
                   "Digital Marketing", "Digital Media", "Digital Signage", "Direct Marketing", "Direct Sales",
                   "Document Management", "Document Preparation", "Domain Registrar", "Drone Management", "Drones",
                   "E-Commerce", "E-Commerce Platforms", "E-Learning", "E-Signature", "EBooks", "EdTech", "Ediscovery",
                   "Education", "Elder Care", "Elderly", "Electric Vehicle", "Electrical Distribution",
                   "Electronic Design Automation (EDA)", "Electronic Health Record (EHR)", "Electronics", "Email",
                   "Email Marketing", "Embedded Software", "Embedded Systems", "Emergency Medicine", "Emerging Markets",
                   "Employee Benefits", "Employment", "Energy", "Energy Efficiency", "Energy Management",
                   "Energy Storage", "Enterprise", "Enterprise Applications", "Enterprise Resource Planning (ERP)",
                   "Enterprise Software", "Entertainment", "Environmental Consulting", "Environmental Engineering",
                   "Ethereum", "Event Management", "Event Promotion", "Events", "Eyewear", "Facebook",
                   "Facial Recognition", "Facilities Support Services", "Facility Management", "Family",
                   "Fantasy Sports", "Farming", "Fashion", "Fast-Moving Consumer Goods", "Field Support",
                   "File Sharing", "Film", "Film Distribution", "Film Production", "FinTech", "Finance",
                   "Financial Exchanges", "Financial Services", "First Aid", "Fitness", "Flash Storage",
                   "Fleet Management", "Flowers", "Food Delivery", "Food Processing", "Food and Beverage", "Franchise",
                   "Fraud Detection", "Freelance", "Freemium", "Freight Service", "Fuel", "Funding Platform",
                   "Funerals", "Furniture", "GPS", "GPU", "Gambling", "Gamification", "Gaming", "Genetics",
                   "Geospatial", "Gift", "Gift Card", "Golf", "Google Glass", "GovTech", "Government", "Graphic Design",
                   "Green Building", "GreenTech", "Grocery", "Group Buying", "Guides", "Hardware", "Health Care",
                   "Health Diagnostics", "Health Insurance", "Hedge Funds", "Higher Education", "Home Decor",
                   "Home Health Care", "Home Improvement", "Home Renovation", "Home Services", "Home and Garden",
                   "Homeland Security", "Hospital", "Hospitality", "Hotel", "Housekeeping Service",
                   "Human Computer Interaction", "Human Resources", "Humanitarian", "ISP", "IT Infrastructure",
                   "IT Management", "IaaS", "Identity Management", "Image Recognition", "Impact Investing",
                   "In-Flight Entertainment", "Incubators", "Independent Music", "Indoor Positioning", "Industrial",
                   "Industrial Automation", "Industrial Design", "Industrial Engineering", "Industrial Manufacturing",
                   "Information Services", "Information Technology", "Information and Communications Technology (ICT)",
                   "Infrastructure", "Innovation Management", "InsurTech", "Insurance", "Intellectual Property",
                   "Intelligent Systems", "Interior Design", "Internet", "Internet Radio", "Internet of Things",
                   "Intrusion Detection", "Jewelry", "Journalism", "Knowledge Management", "LGBT", "Landscaping",
                   "Language Learning", "Laser", "Last Mile Transportation", "Laundry and Dry-cleaning",
                   "Law Enforcement", "Lead Generation", "Lead Management", "Leasing", "Legal", "Legal Tech", "Leisure",
                   "Lending", "Life Insurance", "Life Science", "Lifestyle", "Lighting", "Linux", "Livestock", "Local",
                   "Local Advertising", "Local Business", "Local Shopping", "Location Based Services", "Logistics",
                   "Loyalty Programs", "MMO Games", "Machine Learning", "Machinery Manufacturing", "Made to Order",
                   "Management Consulting", "Management Information Systems", "Manufacturing", "Mapping Services",
                   "Marine Technology", "Marine Transportation", "Market Research", "Marketing", "Marketing Automation",
                   "Marketplace", "Mechanical Design", "Mechanical Engineering", "Media and Entertainment", "Medical",
                   "Medical Device", "Meeting Software", "Men's", "Messaging", "Micro Lending", "Military",
                   "Millennials", "Mineral", "Mining", "Mining Technology", "Mobile", "Mobile Advertising",
                   "Mobile Apps", "Mobile Devices", "Mobile Payments", "Motion Capture", "Music", "Music Education",
                   "Music Label", "Music Streaming", "Music Venues", "Musical Instruments", "NFC", "Nanotechnology",
                   "National Security", "Natural Language Processing", "Natural Resources", "Navigation",
                   "Network Hardware", "Network Security", "Neuroscience", "News", "Nightclubs", "Non Profit",
                   "Nursing and Residential Care", "Nutraceutical", "Nutrition", "Office Administration", "Oil and Gas",
                   "Online Auctions", "Online Forums", "Online Games", "Online Portals", "Open Source",
                   "Operating Systems", "Optical Communication", "Organic", "Organic Food", "Outdoor Advertising",
                   "Outdoors", "Outsourcing", "PC Games", "PaaS", "Packaging Services", "Parenting", "Parking", "Parks",
                   "Payments", "Peer to Peer", "Penetration Testing", "Performing Arts", "Personal Branding",
                   "Personal Development", "Personal Finance", "Personal Health", "Personalization", "Pet",
                   "Pharmaceutical", "Photo Editing", "Photo Sharing", "Photography", "Physical Security", "Podcast",
                   "Point of Sale", "Politics", "Ports and Harbors", "Power Grid", "Precious Metals",
                   "Predictive Analytics", "Presentation Software", "Presentations", "Price Comparison",
                   "Primary Education", "Printing", "Privacy", "Private Cloud", "Private Social Networking",
                   "Procurement", "Product Design", "Product Management", "Product Research", "Product Search",
                   "Productivity Tools", "Professional Networking", "Professional Services", "Project Management",
                   "Property Development", "Property Insurance", "Property Management", "Psychology",
                   "Public Relations", "Public Safety", "Public Transportation", "Publishing", "Q&A", "QR Codes",
                   "Quality Assurance", "Quantified Self", "RFID", "Racing", "Railroad", "Reading Apps", "Real Estate",
                   "Real Estate Investment", "Real Time", "Recreation", "Recreational Vehicles", "Recruiting",
                   "Recycling", "Rehabilitation", "Renewable Energy", "Rental", "Rental Property", "Reputation",
                   "Reservations", "Residential", "Resorts", "Restaurants", "Retail", "Retail Technology", "Retirement",
                   "Ride Sharing", "Risk Management", "Robotics", "SEM", "SEO", "SMS", "SNS", "STEM Education", "SaaS",
                   "Sales", "Sales Automation", "Same Day Delivery", "Satellite Communication", "Scheduling",
                   "Search Engine", "Secondary Education", "Security", "Self-Storage", "Semantic Search",
                   "Semantic Web", "Semiconductor", "Sensor", "Service Industry", "Sharing Economy", "Shipping",
                   "Shoes", "Shopping", "Shopping Mall", "Simulation", "Skill Assessment",
                   "Small and Medium Businesses", "Smart Building", "Smart Cities", "Smart Home", "Snack Food",
                   "Soccer", "Social", "Social Bookmarking", "Social CRM", "Social Entrepreneurship", "Social Impact",
                   "Social Media", "Social Media Advertising", "Social Media Management", "Social Media Marketing",
                   "Social Network", "Social News", "Social Recruiting", "Social Shopping", "Software",
                   "Software Engineering", "Solar", "Space Travel", "Spam Filtering", "Speech Recognition",
                   "Sponsorship", "Sporting Goods", "Sports", "Staffing Agency", "Stock Exchanges",
                   "Subscription Service", "Supply Chain Management", "Surfing", "Sustainability", "TV",
                   "TV Production", "Task Management", "Taxi Service", "Tea", "Technical Support", "Telecommunications",
                   "Tennis", "Test and Measurement", "Text Analytics", "Textbook", "Textiles", "Theatre",
                   "Therapeutics", "Ticketing", "Timber", "Tobacco", "Tourism", "Toys", "Trade Shows",
                   "Trading Platform", "Training", "Transaction Processing", "Translation Service", "Transportation",
                   "Travel", "Travel Accommodations", "Travel Agency", "Tutoring", "Twitter", "UX Design",
                   "Unified Communications", "Universities", "Vacation Rental", "Vending and Concessions",
                   "Venture Capital", "Vertical Search", "Veterinary", "Video", "Video Advertising", "Video Chat",
                   "Video Conferencing", "Video Editing", "Video Games", "Video Streaming", "Video on Demand",
                   "Virtual Assistant", "Virtual Currency", "Virtual Desktop", "Virtual Goods", "Virtual Reality",
                   "Virtual Workforce", "Virtual World", "Virtualization", "Visual Search", "VoIP",
                   "Vocational Education", "Warehousing", "Waste Management", "Water", "Water Purification",
                   "Water Transportation", "Wealth Management", "Wearables", "Web Apps", "Web Browsers", "Web Design",
                   "Web Development", "Web Hosting", "Wedding", "Wellness", "Wholesale", "Wind Energy",
                   "Wine And Spirits", "Wired Telecommunications", "Wireless", "Women's", "Young Adults", "eSports",
                   "iOS", "mHealth", "—"]

UNIQ_FUNDINGTYPES = ["Angel", "Convertible Note", "Corporate Round", "Debt Financing", "Equity Crowdfunding",
                     "Funding Round", "Grant", "Initial Coin Offering", "Non-equity Assistance", "Post-IPO Debt",
                     "Post-IPO Equity", "Post-IPO Secondary", "Pre-Seed", "Private Equity", "Secondary Market", "Seed",
                     "Series A", "Series B", "Series C", "Series D", "Series E", "Series F", "Series G", "Series H",
                     "Series I", "Series J", "Venture - Series Unknown"
                     ]
